<a href="https://colab.research.google.com/github/arethel/kaggle1/blob/main/kaggle1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt

In [2]:
!pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 MB 10.8 MB/s eta 0:00:00


In [4]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import HistGradientBoostingRegressor
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier

In [5]:
from imblearn.over_sampling import RandomOverSampler
from sklearn.metrics import confusion_matrix

In [13]:
train_df = pd.read_csv("train.csv")
train_df

id Product ID Type  Air temperature [K]  Process temperature [K]  \
0            0     L50096    L                300.6                    309.6   
1            1     M20343    M                302.6                    312.1   
2            2     L49454    L                299.3                    308.5   
3            3     L53355    L                301.0                    310.9   
4            4     M24050    M                298.0                    309.0   
...        ...        ...  ...                  ...                      ...   
136424  136424     M22284    M                300.1                    311.4   
136425  136425     H38017    H                297.5                    308.5   
136426  136426     L54690    L                300.5                    311.8   
136427  136427     L53876    L                301.7                    310.9   
136428  136428     L47937    L                296.9                    308.1   

        Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
0                         1596         36.1              140                0   
1                         1759         29.1              200                0   
2                         1805         26.5               25                0   
3                         1524         44.3              197                0   
4                         1641         35.4               34                0   
...                        ...          ...              ...              ...   
136424                    1530         37.5              210                0   
136425                    1447         49.1                2                0   
136426                    1524         38.5              214                0   
136427                    1447         46.3               42                0   
136428                    1557         39.3              229                0   

        TWF  HDF  PWF  OSF  RNF  
0         0    0    0    0    0  
1         0    0    0    0    0  
2         0    0    0    0    0  
3         0    0    0    0    0  
4         0    0    0    0    0  
...     ...  ...  ...  ...  ...  
136424    0    0    0    0    0  
136425    0    0    0    0    0  
136426    0    0    0    0    0  
136427    0    0    0    0    0  
136428    0    0    0    0    0  

[136429 rows x 14 columns]

In [14]:
train_df = train_df.drop(['id', 'Product ID'], axis = 1)
train_df

Type  Air temperature [K]  Process temperature [K]  \
0         L                300.6                    309.6   
1         M                302.6                    312.1   
2         L                299.3                    308.5   
3         L                301.0                    310.9   
4         M                298.0                    309.0   
...     ...                  ...                      ...   
136424    M                300.1                    311.4   
136425    H                297.5                    308.5   
136426    L                300.5                    311.8   
136427    L                301.7                    310.9   
136428    L                296.9                    308.1   

        Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
0                         1596         36.1              140                0   
1                         1759         29.1              200                0   
2                         1805         26.5               25                0   
3                         1524         44.3              197                0   
4                         1641         35.4               34                0   
...                        ...          ...              ...              ...   
136424                    1530         37.5              210                0   
136425                    1447         49.1                2                0   
136426                    1524         38.5              214                0   
136427                    1447         46.3               42                0   
136428                    1557         39.3              229                0   

        TWF  HDF  PWF  OSF  RNF  
0         0    0    0    0    0  
1         0    0    0    0    0  
2         0    0    0    0    0  
3         0    0    0    0    0  
4         0    0    0    0    0  
...     ...  ...  ...  ...  ...  
136424    0    0    0    0    0  
136425    0    0    0    0    0  
136426    0    0    0    0    0  
136427    0    0    0    0    0  
136428    0    0    0    0    0  

[136429 rows x 12 columns]

In [180]:
train_df["Type"] = train_df["Type"].replace({'L':0})
train_df["Type"] = train_df["Type"].replace({'M':1})
train_df["Type"] = train_df["Type"].replace({'H':2})
train_df["Type"] = train_df["Type"].astype(int)
train_df

Type  Air temperature [K]  Process temperature [K]  \
0          0                300.6                    309.6   
1          1                302.6                    312.1   
2          0                299.3                    308.5   
3          0                301.0                    310.9   
4          1                298.0                    309.0   
...      ...                  ...                      ...   
136424     1                300.1                    311.4   
136425     2                297.5                    308.5   
136426     0                300.5                    311.8   
136427     0                301.7                    310.9   
136428     0                296.9                    308.1   

        Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
0                         1596         36.1              140                0   
1                         1759         29.1              200                0   
2                         1805         26.5               25                0   
3                         1524         44.3              197                0   
4                         1641         35.4               34                0   
...                        ...          ...              ...              ...   
136424                    1530         37.5              210                0   
136425                    1447         49.1                2                0   
136426                    1524         38.5              214                0   
136427                    1447         46.3               42                0   
136428                    1557         39.3              229                0   

        TWF  HDF  PWF  OSF  RNF  
0         0    0    0    0    0  
1         0    0    0    0    0  
2         0    0    0    0    0  
3         0    0    0    0    0  
4         0    0    0    0    0  
...     ...  ...  ...  ...  ...  
136424    0    0    0    0    0  
136425    0    0    0    0    0  
136426    0    0    0    0    0  
136427    0    0    0    0    0  
136428    0    0    0    0    0  

[136429 rows x 12 columns]

In [15]:
train_df = pd.concat([pd.get_dummies(train_df['Type']), train_df], axis=1)
train_df = train_df.drop(['Type'], axis = 1)
train_df

H  L  M  Air temperature [K]  Process temperature [K]  \
0       0  1  0                300.6                    309.6   
1       0  0  1                302.6                    312.1   
2       0  1  0                299.3                    308.5   
3       0  1  0                301.0                    310.9   
4       0  0  1                298.0                    309.0   
...    .. .. ..                  ...                      ...   
136424  0  0  1                300.1                    311.4   
136425  1  0  0                297.5                    308.5   
136426  0  1  0                300.5                    311.8   
136427  0  1  0                301.7                    310.9   
136428  0  1  0                296.9                    308.1   

        Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
0                         1596         36.1              140                0   
1                         1759         29.1              200                0   
2                         1805         26.5               25                0   
3                         1524         44.3              197                0   
4                         1641         35.4               34                0   
...                        ...          ...              ...              ...   
136424                    1530         37.5              210                0   
136425                    1447         49.1                2                0   
136426                    1524         38.5              214                0   
136427                    1447         46.3               42                0   
136428                    1557         39.3              229                0   

        TWF  HDF  PWF  OSF  RNF  
0         0    0    0    0    0  
1         0    0    0    0    0  
2         0    0    0    0    0  
3         0    0    0    0    0  
4         0    0    0    0    0  
...     ...  ...  ...  ...  ...  
136424    0    0    0    0    0  
136425    0    0    0    0    0  
136426    0    0    0    0    0  
136427    0    0    0    0    0  
136428    0    0    0    0    0  

[136429 rows x 14 columns]

In [16]:
temp_dif = train_df['Air temperature [K]'] - train_df['Process temperature [K]']
temp_dif.name = 'temp_dif'
temp_dif

0         -9.0
1         -9.5
2         -9.2
3         -9.9
4        -11.0
          ... 
136424   -11.3
136425   -11.0
136426   -11.3
136427    -9.2
136428   -11.2
Name: temp_dif, Length: 136429, dtype: float64

In [17]:
power = train_df['Rotational speed [rpm]'] * train_df['Torque [Nm]']
power.name = 'power'
power

0         57615.6
1         51186.9
2         47832.5
3         67513.2
4         58091.4
           ...   
136424    57375.0
136425    71047.7
136426    58674.0
136427    66996.1
136428    61190.1
Name: power, Length: 136429, dtype: float64

In [19]:
train_df = pd.concat([train_df, power], axis=1)
train_df

H  L  M  Air temperature [K]  Process temperature [K]  \
0       0  1  0                300.6                    309.6   
1       0  0  1                302.6                    312.1   
2       0  1  0                299.3                    308.5   
3       0  1  0                301.0                    310.9   
4       0  0  1                298.0                    309.0   
...    .. .. ..                  ...                      ...   
136424  0  0  1                300.1                    311.4   
136425  1  0  0                297.5                    308.5   
136426  0  1  0                300.5                    311.8   
136427  0  1  0                301.7                    310.9   
136428  0  1  0                296.9                    308.1   

        Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
0                         1596         36.1              140                0   
1                         1759         29.1              200                0   
2                         1805         26.5               25                0   
3                         1524         44.3              197                0   
4                         1641         35.4               34                0   
...                        ...          ...              ...              ...   
136424                    1530         37.5              210                0   
136425                    1447         49.1                2                0   
136426                    1524         38.5              214                0   
136427                    1447         46.3               42                0   
136428                    1557         39.3              229                0   

        TWF  HDF  PWF  OSF  RNF  temp_dif    power  
0         0    0    0    0    0      -9.0  57615.6  
1         0    0    0    0    0      -9.5  51186.9  
2         0    0    0    0    0      -9.2  47832.5  
3         0    0    0    0    0      -9.9  67513.2  
4         0    0    0    0    0     -11.0  58091.4  
...     ...  ...  ...  ...  ...       ...      ...  
136424    0    0    0    0    0     -11.3  57375.0  
136425    0    0    0    0    0     -11.0  71047.7  
136426    0    0    0    0    0     -11.3  58674.0  
136427    0    0    0    0    0      -9.2  66996.1  
136428    0    0    0    0    0     -11.2  61190.1  

[136429 rows x 16 columns]

In [ ]:
train_df = train_df.drop(['airT_pi'], axis = 1)
train_df

H  L  M  Air temperature [K]  Process temperature [K]  \
0       0  1  0                300.6                    309.6   
1       0  0  1                302.6                    312.1   
2       0  1  0                299.3                    308.5   
3       0  1  0                301.0                    310.9   
4       0  0  1                298.0                    309.0   
...    .. .. ..                  ...                      ...   
136424  0  0  1                300.1                    311.4   
136425  1  0  0                297.5                    308.5   
136426  0  1  0                300.5                    311.8   
136427  0  1  0                301.7                    310.9   
136428  0  1  0                296.9                    308.1   

        Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
0                         1596         36.1              140                0   
1                         1759         29.1              200                0   
2                         1805         26.5               25                0   
3                         1524         44.3              197                0   
4                         1641         35.4               34                0   
...                        ...          ...              ...              ...   
136424                    1530         37.5              210                0   
136425                    1447         49.1                2                0   
136426                    1524         38.5              214                0   
136427                    1447         46.3               42                0   
136428                    1557         39.3              229                0   

          power  temp_dif  temp_div  TWF  HDF  PWF  OSF  RNF  temp_dif_impact  \
0       57615.6       9.0  2.994012    0    0    0    0    0           1.2600   
1       51186.9       9.5  3.139458    0    0    0    0    0           1.9000   
2       47832.5       9.2  3.073839    0    0    0    0    0           0.2300   
3       67513.2       9.9  3.289037    0    0    0    0    0           1.9503   
4       58091.4      11.0  3.691275    0    0    0    0    0           0.3740   
...         ...       ...       ...  ...  ...  ...  ...  ...              ...   
136424  57375.0      11.3  3.765412    0    0    0    0    0           2.3730   
136425  71047.7      11.0  3.697479    0    0    0    0    0           0.0220   
136426  58674.0      11.3  3.760399    0    0    0    0    0           2.4182   
136427  66996.1       9.2  3.049387    0    0    0    0    0           0.3864   
136428  61190.1      11.2  3.772314    0    0    0    0    0           2.5648   

        power_impact  
0          80.661840  
1         102.373800  
2          11.958125  
3         133.001004  
4          19.751076  
...              ...  
136424    120.487500  
136425      1.420954  
136426    125.562360  
136427     28.138362  
136428    140.125329  

[136429 rows x 19 columns]

In [ ]:
to_view = np.array(['Air temperature [K]','Process temperature [K]','Rotational speed [rpm]',
                    'Torque [Nm]','Tool wear [min]','power','temp_dif','temp_div','temp_dif_impact','power_impact',
                    'TWF',	'HDF',	'PWF',	'OSF',	'RNF'])

In [ ]:
to_view.shape

(15,)

In [ ]:
def create_plots_for_HLM(dataframe1, dataframe2):
    plt.figure(figsize=(12,30))
    for i, column in enumerate(to_view):
        plt.subplot(15, 6, i*6+1)
        plt.hist(dataframe1.loc[dataframe1['H']==1, column], bins= 30);
        plt.title('H '+column)
        # plt.axis(False)

        plt.subplot(15, 6, i*6+2)
        plt.hist(dataframe1.loc[dataframe1["L"]==1, column], bins= 30);
        plt.title("L "+column)
        # plt.axis(False)

        plt.subplot(15, 6, i*6+3)
        plt.hist(dataframe1.loc[dataframe1['M']==1, column], bins= 30);
        plt.title('M '+ column)
        # plt.axis(False)

        plt.subplot(15, 6, i*6+4)
        plt.hist(dataframe2.loc[dataframe2['H']==1, column], bins= 30);
        plt.title('H '+column)
        # plt.axis(False)

        plt.subplot(15, 6, i*6+5)
        plt.hist(dataframe2.loc[dataframe2["L"]==1, column], bins= 30);
        plt.title("L "+column)
        # plt.axis(False)

        plt.subplot(15, 6, i*6+6)
        plt.hist(dataframe2.loc[dataframe2['M']==1, column], bins= 30);
        plt.title('M '+ column)
        # plt.axis(False)



In [ ]:
create_plots_for_HLM(train_df,train_df.loc[train_df['Machine failure']==0])

In [20]:
ros = RandomOverSampler(random_state=0)

In [21]:
X, y = np.array(train_df.drop(['Machine failure'], axis = 1)), np.array(train_df['Machine failure'])
X.shape, y.shape

((136429, 15), (136429,))

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train.shape, X_test.shape

((109143, 15), (27286, 15))

In [98]:
X_train, y_train = ros.fit_resample(X_train, y_train)

In [85]:
clf = RandomForestClassifier(max_depth=6, n_estimators=100, criterion = 'entropy', class_weight='balanced')

In [86]:
clf.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', criterion='entropy',
                       max_depth=6)

In [87]:
y_preds = clf.predict(X_test)
y_preds[:10], y_preds.shape

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), (27286,))

In [88]:
roc_auc_score(y_test, y_preds)

0.90777286949808

In [91]:
pd.Series(clf.feature_importances_, index=train_df.drop(['Machine failure'], axis = 1).columns).sort_values()

RNF                        0.000027
H                          0.000214
M                          0.000418
L                          0.000822
Process temperature [K]    0.004388
Air temperature [K]        0.030275
Tool wear [min]            0.053298
temp_dif                   0.063042
PWF                        0.073858
TWF                        0.079479
power                      0.094320
OSF                        0.118249
HDF                        0.131574
Rotational speed [rpm]     0.174453
Torque [Nm]                0.175583
dtype: float64

In [92]:
confusion_matrix(y_test, y_preds)

array([[25738,  1108],
       [   63,   377]])

In [195]:
a = np.arange(19)
np.random.shuffle(a)
a

array([14,  1,  6,  7, 11, 12, 10,  8, 17, 15, 18,  9, 13,  3,  2, 16,  5,
        4,  0])

In [15]:
from sklearn.utils import shuffle
from sklearn.ensemble import VotingClassifier

In [16]:
from sklearn.ensemble import HistGradientBoostingClassifier

In [22]:
import sklearn.ensemble as ens

In [26]:
ros = RandomOverSampler(random_state=0)

In [19]:
type(HistGradientBoostingClassifier())

sklearn.ensemble._hist_gradient_boosting.gradient_boosting.HistGradientBoostingClassifier

In [44]:
def get_different_datasets(df, n_features):
    columns = np.array(df.drop(['Machine failure'], axis = 1).columns)
    df_ = df[shuffle(columns)[:n_features]]
    features_to_add = np.array(df_.columns)[:3]
    df_=pd.concat([df_, pd.Series(df_[features_to_add[0]]*df_[features_to_add[1]],name=features_to_add[0]+'*'+features_to_add[1]) ], axis=1)
    df_=pd.concat([df_, pd.Series(df_[features_to_add[0]]-df_[features_to_add[2]],name=features_to_add[0]+'-'+features_to_add[2]) ], axis=1)

    return df_

In [155]:
dtype = [('model', ens._hist_gradient_boosting.gradient_boosting.HistGradientBoostingClassifier),
 ('auc roc', float), ('columns', np.ndarray)]
best_models = np.array([(HistGradientBoostingRegressor(), 0, ['col']),(HistGradientBoostingRegressor(), 0.1, ['col']),
 (HistGradientBoostingRegressor(), 0.2, ['col']),(HistGradientBoostingRegressor(), 0.3, ['col']),
  (HistGradientBoostingRegressor(), 0.4, ['col'])], dtype=dtype)

In [91]:
def save_best_models(new_model):
    global best_models
    # print(new_model)
    if len(best_models)<5:
        best_models = np.append(best_models, (new_model))
    else:
        best_models = np.sort(best_models, order='auc roc')
        if best_models[0][1] < new_model[1]:
            best_models[0] = new_model

In [38]:
different_datasets = get_different_datasets(train_df, 40, 13)

In [387]:
models = []
for i in range(40):
    models.append(('model'+str(i), HistGradientBoostingRegressor()))
models = np.array(models)

In [20]:
type(np.array(different_datasets[0].columns))

numpy.ndarray

In [220]:
i = 0
while True:
    # different_dataset = get_different_datasets(train_df, np.random.randint(7,18))
    different_dataset = ds
    X_train, X_test, y_train, y_test = train_test_split(different_dataset, train_df['Machine failure'], test_size=0.2)
    if np.random.rand(1)[0]<0.5:
        X_train, y_train = ros.fit_resample(X_train, y_train)
    # model = HistGradientBoostingRegressor(l2_regularization=np.random.rand(1)[0]*0.2, max_iter = np.random.randint(50,120), max_depth = np.random.randint(5,20))
    model = HistGradientBoostingRegressor()
    model.set_params(**best_models[4][0].get_params())
    # model = XGBClassifier(random_state=1, n_estimators=128)
    # model = CatBoostClassifier(verbose = 0)
    model.fit(np.array(X_train), np.array(y_train))
    y_preds = model.predict(np.array(X_test))

    roc_score = roc_auc_score(y_test, y_preds)
    # if roc_score>0.97:
    print(f'model {i} score: {roc_score:.5f}')
    save_best_models((model, roc_score, np.array(different_dataset.columns)))
    i+=1
    # print(confusion_matrix(y_test, np.round(y_preds)))

model 0 score: 0.95893
model 1 score: 0.95677
model 2 score: 0.95724
model 3 score: 0.95420
model 4 score: 0.95991
model 5 score: 0.96949
model 6 score: 0.96182
model 7 score: 0.95170
model 8 score: 0.95550
model 9 score: 0.95662
model 10 score: 0.96221
model 11 score: 0.95778
model 12 score: 0.97163
model 13 score: 0.96754
model 14 score: 0.96934
model 15 score: 0.96070
model 16 score: 0.95579
model 17 score: 0.95817
model 18 score: 0.95852
model 19 score: 0.95656
model 20 score: 0.96062
model 21 score: 0.96460
model 22 score: 0.96801
model 23 score: 0.96528
model 24 score: 0.94603
model 25 score: 0.95666


KeyboardInterrupt: ignored

In [189]:
best_models

array([(HistGradientBoostingRegressor(l2_regularization=0.11613067415865733,
                                     max_depth=12, max_iter=72), 0.97676124, array(['Process temperature [K]', 'TWF', 'L', 'temp_dif', 'Torque [Nm]',
              'Air temperature [K]', 'RNF', 'OSF', 'M', 'HDF', 'power', 'PWF',
              'Tool wear [min]', 'H', 'Rotational speed [rpm]',
              'Process temperature [K]*TWF', 'Process temperature [K]-L'],
             dtype=object))                                                                                                                          ,
       (HistGradientBoostingRegressor(l2_regularization=0.007324757146978423,
                                     max_depth=13, max_iter=113), 0.97690095, array(['temp_dif', 'power', 'H', 'Torque [Nm]', 'Tool wear [min]',
              'Process temperature [K]', 'TWF', 'HDF', 'OSF', 'M',
              'Rotational speed [rpm]', 'L', 'RNF', 'PWF', 'Air temperature [K]',
              'temp_dif*power', 

In [213]:
best_models[4][0].get_params()

{'categorical_features': None,
 'early_stopping': 'auto',
 'interaction_cst': None,
 'l2_regularization': 0.04975985060602213,
 'learning_rate': 0.1,
 'loss': 'squared_error',
 'max_bins': 255,
 'max_depth': 5,
 'max_iter': 79,
 'max_leaf_nodes': 31,
 'min_samples_leaf': 20,
 'monotonic_cst': None,
 'n_iter_no_change': 10,
 'quantile': None,
 'random_state': None,
 'scoring': 'loss',
 'tol': 1e-07,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [191]:
best_models[4][2]

array(['OSF', 'power', 'Process temperature [K]', 'M', 'TWF', 'H',
       'Torque [Nm]', 'HDF', 'Air temperature [K]', 'RNF',
       'Rotational speed [rpm]', 'L', 'Tool wear [min]', 'temp_dif',
       'PWF', 'OSF*power', 'OSF-Process temperature [K]'], dtype=object)

In [210]:
def get_different_datasets_by_columns(df, columns):
    columns = columns[:-2]
    df_ = df[columns]
    features_to_add = np.array(df_.columns)[:3]
    df_=pd.concat([df_, pd.Series(df_[features_to_add[0]]*df_[features_to_add[1]],name=features_to_add[0]+'*'+features_to_add[1]) ], axis=1)
    df_=pd.concat([df_, pd.Series(df_[features_to_add[0]]-df_[features_to_add[2]],name=features_to_add[0]+'-'+features_to_add[2]) ], axis=1)

    return df_

In [211]:
ds = get_different_datasets_by_columns(train_df, best_models[4][2])

In [134]:
test_df = pd.read_csv('test.csv')

In [135]:
test_df

id Product ID Type  Air temperature [K]  Process temperature [K]  \
0      136429     L50896    L                302.3                    311.5   
1      136430     L53866    L                301.7                    311.0   
2      136431     L50498    L                301.3                    310.4   
3      136432     M21232    M                300.1                    309.6   
4      136433     M19751    M                303.4                    312.3   
...       ...        ...  ...                  ...                      ...   
90949  227378     L51130    L                302.3                    311.4   
90950  227379     L47783    L                297.9                    309.8   
90951  227380     L48097    L                295.6                    306.2   
90952  227381     L48969    L                298.1                    307.8   
90953  227382     L52525    L                303.5                    312.8   

       Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  \
0                        1499         38.0               60    0    0    0   
1                        1713         28.8               17    0    0    0   
2                        1525         37.7               96    0    0    0   
3                        1479         47.6                5    0    0    0   
4                        1515         41.3              114    0    0    0   
...                       ...          ...              ...  ...  ...  ...   
90949                    1484         40.4               15    0    0    0   
90950                    1542         33.8               31    0    0    0   
90951                    1501         41.4              187    0    0    0   
90952                    1534         40.3               69    0    0    0   
90953                    1534         36.1               92    0    0    0   

       OSF  RNF  
0        0    0  
1        0    0  
2        0    0  
3        0    0  
4        0    0  
...    ...  ...  
90949    0    0  
90950    0    0  
90951    0    0  
90952    0    0  
90953    0    0  

[90954 rows x 13 columns]

In [136]:
test_df = test_df.drop(['id', 'Product ID'], axis = 1)
test_df = pd.concat([pd.get_dummies(test_df['Type']), test_df], axis=1)
test_df = test_df.drop(['Type'], axis = 1)
test_df


H  L  M  Air temperature [K]  Process temperature [K]  \
0      0  1  0                302.3                    311.5   
1      0  1  0                301.7                    311.0   
2      0  1  0                301.3                    310.4   
3      0  0  1                300.1                    309.6   
4      0  0  1                303.4                    312.3   
...   .. .. ..                  ...                      ...   
90949  0  1  0                302.3                    311.4   
90950  0  1  0                297.9                    309.8   
90951  0  1  0                295.6                    306.2   
90952  0  1  0                298.1                    307.8   
90953  0  1  0                303.5                    312.8   

       Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  \
0                        1499         38.0               60    0    0    0   
1                        1713         28.8               17    0    0    0   
2                        1525         37.7               96    0    0    0   
3                        1479         47.6                5    0    0    0   
4                        1515         41.3              114    0    0    0   
...                       ...          ...              ...  ...  ...  ...   
90949                    1484         40.4               15    0    0    0   
90950                    1542         33.8               31    0    0    0   
90951                    1501         41.4              187    0    0    0   
90952                    1534         40.3               69    0    0    0   
90953                    1534         36.1               92    0    0    0   

       OSF  RNF  
0        0    0  
1        0    0  
2        0    0  
3        0    0  
4        0    0  
...    ...  ...  
90949    0    0  
90950    0    0  
90951    0    0  
90952    0    0  
90953    0    0  

[90954 rows x 13 columns]

In [137]:
temp_dif = test_df['Air temperature [K]'] - test_df['Process temperature [K]']
temp_dif.name = 'temp_dif'
test_df = pd.concat([test_df, temp_dif], axis=1)
test_df

H  L  M  Air temperature [K]  Process temperature [K]  \
0      0  1  0                302.3                    311.5   
1      0  1  0                301.7                    311.0   
2      0  1  0                301.3                    310.4   
3      0  0  1                300.1                    309.6   
4      0  0  1                303.4                    312.3   
...   .. .. ..                  ...                      ...   
90949  0  1  0                302.3                    311.4   
90950  0  1  0                297.9                    309.8   
90951  0  1  0                295.6                    306.2   
90952  0  1  0                298.1                    307.8   
90953  0  1  0                303.5                    312.8   

       Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  \
0                        1499         38.0               60    0    0    0   
1                        1713         28.8               17    0    0    0   
2                        1525         37.7               96    0    0    0   
3                        1479         47.6                5    0    0    0   
4                        1515         41.3              114    0    0    0   
...                       ...          ...              ...  ...  ...  ...   
90949                    1484         40.4               15    0    0    0   
90950                    1542         33.8               31    0    0    0   
90951                    1501         41.4              187    0    0    0   
90952                    1534         40.3               69    0    0    0   
90953                    1534         36.1               92    0    0    0   

       OSF  RNF  temp_dif  
0        0    0      -9.2  
1        0    0      -9.3  
2        0    0      -9.1  
3        0    0      -9.5  
4        0    0      -8.9  
...    ...  ...       ...  
90949    0    0      -9.1  
90950    0    0     -11.9  
90951    0    0     -10.6  
90952    0    0      -9.7  
90953    0    0      -9.3  

[90954 rows x 14 columns]

In [138]:
power = test_df['Rotational speed [rpm]'] * test_df['Torque [Nm]']
power.name = 'power'
test_df = pd.concat([test_df, power], axis=1)
test_df

H  L  M  Air temperature [K]  Process temperature [K]  \
0      0  1  0                302.3                    311.5   
1      0  1  0                301.7                    311.0   
2      0  1  0                301.3                    310.4   
3      0  0  1                300.1                    309.6   
4      0  0  1                303.4                    312.3   
...   .. .. ..                  ...                      ...   
90949  0  1  0                302.3                    311.4   
90950  0  1  0                297.9                    309.8   
90951  0  1  0                295.6                    306.2   
90952  0  1  0                298.1                    307.8   
90953  0  1  0                303.5                    312.8   

       Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  \
0                        1499         38.0               60    0    0    0   
1                        1713         28.8               17    0    0    0   
2                        1525         37.7               96    0    0    0   
3                        1479         47.6                5    0    0    0   
4                        1515         41.3              114    0    0    0   
...                       ...          ...              ...  ...  ...  ...   
90949                    1484         40.4               15    0    0    0   
90950                    1542         33.8               31    0    0    0   
90951                    1501         41.4              187    0    0    0   
90952                    1534         40.3               69    0    0    0   
90953                    1534         36.1               92    0    0    0   

       OSF  RNF  temp_dif    power  
0        0    0      -9.2  56962.0  
1        0    0      -9.3  49334.4  
2        0    0      -9.1  57492.5  
3        0    0      -9.5  70400.4  
4        0    0      -8.9  62569.5  
...    ...  ...       ...      ...  
90949    0    0      -9.1  59953.6  
90950    0    0     -11.9  52119.6  
90951    0    0     -10.6  62141.4  
90952    0    0      -9.7  61820.2  
90953    0    0      -9.3  55377.4  

[90954 rows x 15 columns]

In [140]:
temp_dif = test_df['Process temperature [K]'] * test_df['Air temperature [K]']
temp_dif.name = 'Process temperature [K]*Air temperature [K]'
test_df = pd.concat([test_df, temp_dif], axis=1)
test_df

H  L  M  Air temperature [K]  Process temperature [K]  \
0      0  1  0                302.3                    311.5   
1      0  1  0                301.7                    311.0   
2      0  1  0                301.3                    310.4   
3      0  0  1                300.1                    309.6   
4      0  0  1                303.4                    312.3   
...   .. .. ..                  ...                      ...   
90949  0  1  0                302.3                    311.4   
90950  0  1  0                297.9                    309.8   
90951  0  1  0                295.6                    306.2   
90952  0  1  0                298.1                    307.8   
90953  0  1  0                303.5                    312.8   

       Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  \
0                        1499         38.0               60    0    0    0   
1                        1713         28.8               17    0    0    0   
2                        1525         37.7               96    0    0    0   
3                        1479         47.6                5    0    0    0   
4                        1515         41.3              114    0    0    0   
...                       ...          ...              ...  ...  ...  ...   
90949                    1484         40.4               15    0    0    0   
90950                    1542         33.8               31    0    0    0   
90951                    1501         41.4              187    0    0    0   
90952                    1534         40.3               69    0    0    0   
90953                    1534         36.1               92    0    0    0   

       OSF  RNF  temp_dif    power  Process temperature [K]-Torque [Nm]  \
0        0    0      -9.2  56962.0                                273.5   
1        0    0      -9.3  49334.4                                282.2   
2        0    0      -9.1  57492.5                                272.7   
3        0    0      -9.5  70400.4                                262.0   
4        0    0      -8.9  62569.5                                271.0   
...    ...  ...       ...      ...                                  ...   
90949    0    0      -9.1  59953.6                                271.0   
90950    0    0     -11.9  52119.6                                276.0   
90951    0    0     -10.6  62141.4                                264.8   
90952    0    0      -9.7  61820.2                                267.5   
90953    0    0      -9.3  55377.4                                276.7   

       Process temperature [K]*Air temperature [K]  
0                                         94166.45  
1                                         93828.70  
2                                         93523.52  
3                                         92910.96  
4                                         94751.82  
...                                            ...  
90949                                     94136.22  
90950                                     92289.42  
90951                                     90512.72  
90952                                     91755.18  
90953                                     94934.80  

[90954 rows x 17 columns]

In [139]:
temp_dif = test_df['Process temperature [K]'] - test_df['Torque [Nm]']
temp_dif.name = 'Process temperature [K]-Torque [Nm]'
test_df = pd.concat([test_df, temp_dif], axis=1)
test_df

H  L  M  Air temperature [K]  Process temperature [K]  \
0      0  1  0                302.3                    311.5   
1      0  1  0                301.7                    311.0   
2      0  1  0                301.3                    310.4   
3      0  0  1                300.1                    309.6   
4      0  0  1                303.4                    312.3   
...   .. .. ..                  ...                      ...   
90949  0  1  0                302.3                    311.4   
90950  0  1  0                297.9                    309.8   
90951  0  1  0                295.6                    306.2   
90952  0  1  0                298.1                    307.8   
90953  0  1  0                303.5                    312.8   

       Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  \
0                        1499         38.0               60    0    0    0   
1                        1713         28.8               17    0    0    0   
2                        1525         37.7               96    0    0    0   
3                        1479         47.6                5    0    0    0   
4                        1515         41.3              114    0    0    0   
...                       ...          ...              ...  ...  ...  ...   
90949                    1484         40.4               15    0    0    0   
90950                    1542         33.8               31    0    0    0   
90951                    1501         41.4              187    0    0    0   
90952                    1534         40.3               69    0    0    0   
90953                    1534         36.1               92    0    0    0   

       OSF  RNF  temp_dif    power  Process temperature [K]-Torque [Nm]  
0        0    0      -9.2  56962.0                                273.5  
1        0    0      -9.3  49334.4                                282.2  
2        0    0      -9.1  57492.5                                272.7  
3        0    0      -9.5  70400.4                                262.0  
4        0    0      -8.9  62569.5                                271.0  
...    ...  ...       ...      ...                                  ...  
90949    0    0      -9.1  59953.6                                271.0  
90950    0    0     -11.9  52119.6                                276.0  
90951    0    0     -10.6  62141.4                                264.8  
90952    0    0      -9.7  61820.2                                267.5  
90953    0    0      -9.3  55377.4                                276.7  

[90954 rows x 16 columns]

In [141]:
test_df = test_df[best_models[4][2]]

In [142]:
test_df

Process temperature [K]  Air temperature [K]  Torque [Nm]  \
0                        311.5                302.3         38.0   
1                        311.0                301.7         28.8   
2                        310.4                301.3         37.7   
3                        309.6                300.1         47.6   
4                        312.3                303.4         41.3   
...                        ...                  ...          ...   
90949                    311.4                302.3         40.4   
90950                    309.8                297.9         33.8   
90951                    306.2                295.6         41.4   
90952                    307.8                298.1         40.3   
90953                    312.8                303.5         36.1   

       Tool wear [min]  RNF  OSF  TWF  L  Rotational speed [rpm]  HDF  \
0                   60    0    0    0  1                    1499    0   
1                   17    0    0    0  1                    1713    0   
2                   96    0    0    0  1                    1525    0   
3                    5    0    0    0  0                    1479    0   
4                  114    0    0    0  0                    1515    0   
...                ...  ...  ...  ... ..                     ...  ...   
90949               15    0    0    0  1                    1484    0   
90950               31    0    0    0  1                    1542    0   
90951              187    0    0    0  1                    1501    0   
90952               69    0    0    0  1                    1534    0   
90953               92    0    0    0  1                    1534    0   

       temp_dif  H  M  PWF    power  \
0          -9.2  0  0    0  56962.0   
1          -9.3  0  0    0  49334.4   
2          -9.1  0  0    0  57492.5   
3          -9.5  0  1    0  70400.4   
4          -8.9  0  1    0  62569.5   
...         ... .. ..  ...      ...   
90949      -9.1  0  0    0  59953.6   
90950     -11.9  0  0    0  52119.6   
90951     -10.6  0  0    0  62141.4   
90952      -9.7  0  0    0  61820.2   
90953      -9.3  0  0    0  55377.4   

       Process temperature [K]*Air temperature [K]  \
0                                         94166.45   
1                                         93828.70   
2                                         93523.52   
3                                         92910.96   
4                                         94751.82   
...                                            ...   
90949                                     94136.22   
90950                                     92289.42   
90951                                     90512.72   
90952                                     91755.18   
90953                                     94934.80   

       Process temperature [K]-Torque [Nm]  
0                                    273.5  
1                                    282.2  
2                                    272.7  
3                                    262.0  
4                                    271.0  
...                                    ...  
90949                                271.0  
90950                                276.0  
90951                                264.8  
90952                                267.5  
90953                                276.7  

[90954 rows x 17 columns]

In [143]:
best_model = best_models[4][0]

In [145]:
y_subm_preds = best_model.predict(test_df)

In [147]:
pd.Series(y_subm_preds)

0        0.031719
1        0.060330
2        0.029562
3        0.029788
4        0.044198
           ...   
90949    0.033406
90950    0.072998
90951    0.188008
90952    0.019126
90953    0.017662
Length: 90954, dtype: float64

In [148]:
submission = pd.read_csv('sample_submission.csv')

In [150]:
submission['Machine failure'] = y_subm_preds

In [151]:
submission

id  Machine failure
0      136429         0.031719
1      136430         0.060330
2      136431         0.029562
3      136432         0.029788
4      136433         0.044198
...       ...              ...
90949  227378         0.033406
90950  227379         0.072998
90951  227380         0.188008
90952  227381         0.019126
90953  227382         0.017662

[90954 rows x 2 columns]

In [153]:
submission.to_csv('submission.csv', index=False)

In [230]:
X_train, X_test, y_train, y_test = train_test_split(train_df.drop(['Machine failure'], axis=1), train_df['Machine failure'], test_size=0.2)

In [231]:
X_train

H  L  M  Air temperature [K]  Process temperature [K]  \
96823   0  0  1                301.5                    310.5   
29270   0  1  0                298.7                    309.7   
66500   0  0  1                300.4                    309.1   
63575   0  1  0                298.2                    308.0   
88339   0  1  0                299.8                    311.2   
...    .. .. ..                  ...                      ...   
1122    0  1  0                297.5                    308.6   
28797   0  0  1                297.5                    308.9   
127504  0  1  0                300.7                    310.8   
107630  0  1  0                302.0                    310.6   
127038  0  1  0                300.1                    311.5   

        Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  \
96823                     1774         49.7              121    0    0    0   
29270                     1601         35.7               92    0    0    0   
66500                     1352         57.9                0    0    0    0   
63575                     1635         35.8              160    0    0    0   
88339                     1474         46.5              165    0    0    0   
...                        ...          ...              ...  ...  ...  ...   
1122                      1331         54.5                9    0    0    0   
28797                     1436         44.8               94    0    0    0   
127504                    1395         48.5               98    0    0    0   
107630                    1350         57.4               29    0    0    0   
127038                    1462         41.4              162    0    0    0   

        OSF  RNF  temp_dif    power  
96823     0    0      -9.0  88167.8  
29270     0    0     -11.0  57155.7  
66500     0    0      -8.7  78280.8  
63575     0    0      -9.8  58533.0  
88339     0    0     -11.4  68541.0  
...     ...  ...       ...      ...  
1122      0    0     -11.1  72539.5  
28797     0    0     -11.4  64332.8  
127504    0    0     -10.1  67657.5  
107630    0    0      -8.6  77490.0  
127038    0    0     -11.4  60526.8  

[109143 rows x 15 columns]

In [350]:
y_preds = best_model1[1].predict(X_test)
print(roc_auc_score(y_test, y_preds))
print(confusion_matrix(y_test, np.round(y_preds)))

0.9944030853887338
[[26377   519]
 [   23   367]]


In [289]:
best_model1 = models[17]
best_ds1 = different_datasets[17]

In [351]:
best_ds1

temp_dif  HDF  Air temperature [K]  Tool wear [min]  OSF  L  PWF  TWF  \
0           -9.0    0                300.6              140    0  1    0    0   
1           -9.5    0                302.6              200    0  0    0    0   
2           -9.2    0                299.3               25    0  1    0    0   
3           -9.9    0                301.0              197    0  1    0    0   
4          -11.0    0                298.0               34    0  0    0    0   
...          ...  ...                  ...              ...  ... ..  ...  ...   
136424     -11.3    0                300.1              210    0  0    0    0   
136425     -11.0    0                297.5                2    0  0    0    0   
136426     -11.3    0                300.5              214    0  1    0    0   
136427      -9.2    0                301.7               42    0  1    0    0   
136428     -11.2    0                296.9              229    0  1    0    0   

        RNF  Process temperature [K]  Torque [Nm]  Rotational speed [rpm]  H  
0         0                    309.6         36.1                    1596  0  
1         0                    312.1         29.1                    1759  0  
2         0                    308.5         26.5                    1805  0  
3         0                    310.9         44.3                    1524  0  
4         0                    309.0         35.4                    1641  0  
...     ...                      ...          ...                     ... ..  
136424    0                    311.4         37.5                    1530  0  
136425    0                    308.5         49.1                    1447  1  
136426    0                    311.8         38.5                    1524  0  
136427    0                    310.9         46.3                    1447  0  
136428    0                    308.1         39.3                    1557  0  

[136429 rows x 13 columns]

In [357]:
train_df2 = shuffle(train_df)

In [358]:
X_set, y_set = train_df2.drop(['Machine failure'], axis = 1), train_df2['Machine failure']

In [359]:
X_set = X_set[np.array(best_ds1.columns)]

In [360]:
cv_sets = []
set_len = len(y_set)/5
for i in range(5):
    cv_sets.append([X_set.iloc[int(set_len*i):int(set_len*(i+1))], y_set.iloc[int(set_len*i):int(set_len*(i+1))]])

In [361]:
fin_cv_sets = []
for i in range(5):
    set_X = pd.DataFrame()
    set_y = pd.Series()
    for j in range(5):
        if j != i :
            set_X = pd.concat([set_X,cv_sets[j][0]])
            set_y = pd.concat([set_y,cv_sets[j][1]])
    fin_cv_sets.append([set_X, set_y, cv_sets[i][0], cv_sets[i][1]]);


<ipython-input-361-4349dbc6bf79>:4: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  set_y = pd.Series()
<ipython-input-361-4349dbc6bf79>:4: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  set_y = pd.Series()
<ipython-input-361-4349dbc6bf79>:4: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  set_y = pd.Series()
<ipython-input-361-4349dbc6bf79>:4: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  set_y = pd.Series()
<ipython-input-361-4349dbc6bf79>:4: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' 

In [368]:
final_set_X = pd.DataFrame()
final_set_y = pd.Series()
for i , ds in enumerate(fin_cv_sets):
    X_tr, y_tr, X_te, y_te = ds[0], ds[1], ds[2], ds[3]
    model = HistGradientBoostingRegressor()
    model.fit(X_tr, y_tr)
    y_pr = model.predict(X_te)
    X_te = pd.concat([X_te, pd.Series(np.round(y_pr),index=X_te.index, name='mf_added')], axis=1)
    final_set_X = pd.concat([final_set_X, X_te])
    final_set_y = pd.concat([final_set_y, y_te])
    print(roc_auc_score(y_te, y_pr))
    print(confusion_matrix(y_te, np.round(y_pr)))

<ipython-input-368-886bb3bacce8>:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  final_set_y = pd.Series()


0.9648887132131101
[[26852     4]
 [   89   340]]
0.9533485017285837
[[26853     2]
 [   98   333]]
0.9470472534656985
[[26812     4]
 [  127   343]]
0.9477898445922849
[[26844     0]
 [   98   344]]
0.9634874324976084
[[26906     4]
 [   96   280]]


In [371]:
final_set_X

temp_dif  HDF  Air temperature [K]  Tool wear [min]  OSF  L  PWF  TWF  \
41264      -11.1    0                297.8               26    0  1    0    0   
23247      -10.0    0                298.6              180    0  0    0    0   
128183      -9.7    0                297.8              153    0  1    0    0   
129760     -10.7    0                297.2               15    0  0    0    0   
73469      -11.1    0                298.4              117    0  1    0    0   
...          ...  ...                  ...              ...  ... ..  ...  ...   
106649      -9.2    0                301.2              117    0  0    0    0   
6986        -8.8    0                303.7              163    0  0    0    0   
93361      -11.1    0                297.1                2    0  0    0    0   
91554       -8.8    0                300.7              166    0  1    0    0   
37005      -11.2    0                296.9               64    0  1    0    0   

        RNF  Process temperature [K]  Torque [Nm]  Rotational speed [rpm]  H  \
41264     0                    308.9         30.4                    1631  0   
23247     0                    308.6         47.6                    1420  1   
128183    0                    307.5         43.0                    1474  0   
129760    0                    307.9         35.7                    1541  0   
73469     0                    309.5         50.9                    1391  0   
...     ...                      ...          ...                     ... ..   
106649    0                    310.4         37.6                    1482  0   
6986      0                    312.5         45.5                    1470  1   
93361     0                    308.2         34.6                    1651  0   
91554     0                    309.5         52.1                    1389  0   
37005     0                    308.1         38.0                    1556  0   

        mf_added  
41264        0.0  
23247        0.0  
128183       0.0  
129760       0.0  
73469        0.0  
...          ...  
106649       0.0  
6986         0.0  
93361        0.0  
91554        0.0  
37005        0.0  

[136429 rows x 14 columns]

In [375]:
X_train, X_test, y_train, y_test = train_test_split(final_set_X, final_set_y, test_size=0.2)
model = RandomForestClassifier(max_depth=10, n_estimators=100, criterion = 'entropy', class_weight='balanced')
model.fit(X_train, y_train)
y_pr = model.predict(X_test)
print(roc_auc_score(y_test, y_pr))
print(confusion_matrix(y_test, np.round(y_pr)))

0.8907166878161498
[[26727   133]
 [   91   335]]


In [353]:
pd.Series(y_pr, name='mf_added')

0        0.001155
1        0.001433
2        0.001155
3        0.001155
4        0.001951
           ...   
27281    0.047342
27282    0.001768
27283    0.001490
27284    0.001296
27285    0.001433
Name: mf_added, Length: 27286, dtype: float64

In [254]:
def ensemble_models(models):
    preds = []
    for i, (name, model) in enumerate(models):
        X_train, X_test, y_train, y_test = train_test_split(different_datasets[i], train_df['Machine failure'], test_size=0.2)
        preds.append(model.predict(X_test))
    preds = np.array(preds).T
    # print(preds[:10])
    preds = np.max(preds, axis=1)
    # print(preds[:10])
    print(roc_auc_score(y_test, preds))
    print(confusion_matrix(y_test, np.round(preds)))

In [255]:
ensemble_models(models[:3])

0.9467604148340371
[[22561  4319]
 [   35   371]]


In [93]:
clf2 = GradientBoostingClassifier(n_estimators=100, learning_rate=0.01, max_depth=10, random_state=0)

In [94]:
clf2.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.01, max_depth=10, random_state=0)

In [95]:
y_preds = clf2.predict(X_test)
y_preds[:10], y_preds.shape

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), (27286,))

In [96]:
roc_auc_score(y_test, y_preds)

0.8749627505028682

In [97]:
confusion_matrix(y_test, y_preds)

array([[26844,     2],
       [  110,   330]])

In [23]:
from sklearn.preprocessing import normalize

In [24]:
import torch
from torch import nn

In [530]:
train_df2 = train_df

In [535]:
np.array(train_df2.columns).shape

(589,)

In [278]:
features_arr = ['H', 'L', 'M', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF','Machine failure']

In [534]:
cols = np.array(train_df2.columns)
k = 0
for i, column in enumerate(cols):
    for j, column2 in enumerate(cols):
        if(k>500):
            break
        if np.random.rand(1)[0]<0.5:
            continue
        if column in features_arr or column2 in features_arr:
            continue
        if i<j:
            train_df2=pd.concat([train_df2, pd.Series(train_df2[column]*train_df2[column2],name=column+'*'+column2) ], axis=1)
            k+=1
        print(k)
    if(k>500):
        break

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
89
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
128
128
128
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
161
161
161
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
203
203
203
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
240
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261

In [532]:
cols = np.array(train_df2.columns).copy()
for i, column in enumerate(cols):
    for j, column2 in enumerate(cols):
        if column in features_arr or column2 in features_arr:
            continue
        if i<j:
            train_df2=pd.concat([train_df2, pd.Series(train_df2[column]-train_df2[column2],name=column+'-'+column2) ], axis=1)

In [533]:
# cols = np.array(train_df2.columns)
for i, column in enumerate(cols):
    for j, column2 in enumerate(cols):
        if column in features_arr or column2 in features_arr:
            continue
        if i<j:
            train_df2=pd.concat([train_df2, pd.Series(train_df2[column]+train_df2[column2],name=column+'+'+column2) ], axis=1)

In [536]:
train_df2[['Air temperature [K]', 'Process temperature [K]']] = normalize(train_df2[['Air temperature [K]', 'Process temperature [K]']])

In [537]:
X_train, X_test, y_train, y_test = train_test_split(train_df2.drop(['Machine failure'], axis=1), train_df2['Machine failure'], test_size=0.2)

In [502]:
def normalize_(arr, arr_n):
    return (arr-np.min(arr_n))/(np.max(arr_n)-np.min(arr_n))

In [538]:
for i in np.array(X_test.columns):
    if not i in  ['Air temperature [K]', 'Process temperature [K]']:
        X_test[i] = normalize_(X_test[i], X_train[i])

In [539]:
for i in np.array(X_train.columns):
    if not i in  ['Air temperature [K]', 'Process temperature [K]']:
        X_train[i] = normalize_(X_train[i], X_train[i])

In [540]:
X_train, y_train = ros.fit_resample(X_train, y_train)

In [27]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [28]:
device

'cuda'

In [541]:
X_train_T, y_train_T, X_test_T, y_test_T = torch.Tensor(np.array(X_train)).to(device), torch.Tensor(np.array(y_train)).to(device), torch.Tensor(np.array(X_test)).to(device), torch.Tensor(np.array(y_test)).to(device)

In [542]:
class ClassifingModelV0(nn.Module):
    def __init__(self):
        super().__init__()
        hidden = 20
        self.layer_stack = nn.Sequential(
            nn.Linear(588, hidden),
            nn.ReLU(),
            # nn.LayerNorm(40),
            nn.Linear(hidden, hidden),
            nn.ReLU(),
            # nn.LayerNorm(40),
            # nn.Linear(100, 100),
            # nn.ReLU(),
            nn.Linear(hidden, 1)
        )

    def forward(self, x):
        return self.layer_stack(x)

In [543]:
model_0 = ClassifingModelV0().to(device)

In [544]:
loss_fn = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model_0.parameters(), lr=0.0001)

In [545]:
epochs = 10000
max_ar = 0
for epoch in range(epochs):

    model_0.train()
    y_logits = model_0(X_train_T).squeeze()
    # y_pred = torch.sigmoid(y_logits)
    # auc_roc = roc_auc_score(y_train_T.detach().numpy(), y_pred)
    loss = loss_fn(y_logits, y_train_T)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


    if epoch % 1000 == 0:
        model_0.eval()
        with torch.inference_mode():
            y_logits_test = model_0(X_test_T).squeeze()
            y_pred_test = torch.sigmoid(y_logits_test)
            loss_test = loss_fn(y_logits_test, y_test_T)
            auc_roc_test = roc_auc_score(y_test_T.cpu(), y_pred_test.cpu())
            # if(max_ar<auc_roc_test):
            #     max_ar=auc_roc_test
        print(f'Epoch: {epoch} Loss: {loss:.2f} Test loss: {loss_test:.2f} Test auc roc: {auc_roc_test:.5f}')


ValueError: ignored

In [407]:
model_0.eval()
with torch.inference_mode():
    y_logits_test = model_0(X_test_T).squeeze()
    y_pred_test = torch.sigmoid(y_logits_test)
    print(roc_auc_score(y_test_T.cpu(), y_pred_test.cpu()))
    print(confusion_matrix(y_test_T.cpu().numpy(), np.round(y_pred_test.cpu().numpy())))

0.9679236697342788
[[25881   968]
 [   51   386]]
